---
 - name: sshd config
   template: src=sshd_config.j2 dest=/etc/ssh/sshd_config owner=root group=wheel mode=0400
   when: config_options.sshd.is_enabled
   notify: restart sshd
   tags: sshd

 - include: rc.yml
   when: config_options.rc.is_enabled

 # PF rules create quickly (before ssh bruteforce banish), if curent ip could be block if not present in the whitelist
 - include: pf.yml

 - include: ntpd.yml
   when: config_options.ntpd.is_enabled

 - name: loader.conf
   template: src=loader.conf.j2 dest=/boot/loader.conf owner=root group=wheel mode=0400

 - name: Be sure security sysctl flags are configured
   sysctl: name={{ item.name }} value={{ item.value }} state=present checks=none reload=yes
   with_items: sysctl_flags

 - name: Be sure Motd exist
   template: src=motd.j2 dest=/etc/motd  

 - include: pkgng.yml
   when: config_options.pkgng.is_enabled
